services:
  api:
    image: video-streaming-platform-api:latest
    container_name: streaming_platform_api
    volumes:
      - type: bind
        source: /mnt/hdd0/videos
        target: /videos/videos1
      - type: bind
        source: /mnt/hdd0/videos
        target: /videos/videos2
      - type: volume
        source: thumbnails
        target: /thumbnails
      - type: volume
        source: snapshots
        target: /snapshots
    ports:
      - 8085:8080/tcp
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - stack.env
  db:
    image: postgres:latest
    container_name: streaming_platform_db
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    restart: unless-stopped

volumes:
  thumbnails:
  snapshots:
  db:
