spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: Jemoeder10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
env:
  videos:
    root: C:/Users/nwbva/Downloads/videos
  thumbnail:
    root: C:/Users/nwbva/Downloads/thumbnails
    width: 600
    height: 900
  ffprobe:
    path: C:/ffmpeg/bin/ffprobe.exe

